# Generated by Django 4.1.7 on 2023-02-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detections',
            fields=[
                ('detectionId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('classification', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=17)),
                ('evidence', models.CharField(max_length=10485760)),
            ],
        ),
    ]
