# Generated by Django 4.1.7 on 2023-02-16 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saveresults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detections',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detections',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
